In [1]:
#numpy is a library that allows for the use of arrys and matrices
import numpy as np

In [2]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a)
print(b)

[1 2 3]
[4 5 6]


In [3]:
type(a)

numpy.ndarray

In [4]:
print(a+b)
print(a-b)
print(a*b)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]


In [6]:
#creating a 2d array
a = np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [8]:
#creating a 3d array
b = np.array([[[1,2,],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
#creating an arrya with a spacific data type
print(a.dtype)

int64


In [ ]:
#to get the number of dimensions of an array
print(a.ndim)

2


In [11]:
print(a.shape)

(2, 3)


In [13]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(2,11)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
np.arange(2,11,2)

array([ 2,  4,  6,  8, 10])

In [18]:
np.random.randint(10,30)

22

In [19]:
np.random.randint(10,30, size=(3,3))

array([[23, 28, 15],
       [11, 29, 29],
       [18, 23, 16]], dtype=int32)

In [21]:
x = np.array([[7,2,3],[2,5,2],[3,5,1]])
y = np.array([[1,8,3],[3,7,2],[2,5,3]])
print(x)
print(y)

[[7 2 3]
 [2 5 2]
 [3 5 1]]
[[1 8 3]
 [3 7 2]
 [2 5 3]]


In [22]:
print(x*y)

[[ 7 16  9]
 [ 6 35  4]
 [ 6 25  3]]


In [23]:
# matrix multication
print(x@y)

[[19 85 34]
 [21 61 22]
 [20 64 22]]


In [24]:
print(x.dot(y))

[[19 85 34]
 [21 61 22]
 [20 64 22]]


In [25]:
x.prod()

np.int64(12600)

In [26]:
x.mean()

np.float64(3.3333333333333335)

In [27]:
x.mean(axis=0) #mean of the each column

array([4., 4., 2.])

In [28]:
x.mean(axis=1) #mean of each row

array([4., 3., 3.])

In [30]:
print(x.sum())
print(x.var())
print(x.std())

30
3.3333333333333335
1.8257418583505538


In [ ]:
z = np.array([1,2,3,4,5,6,7,8,9])
print(np.percentile(z,25)) #25th percentile
print(np.percentile(z,50)) #50th percentile
print(np.percentile(z,75)) #75th percentile

3.0
5.0
7.0


In [32]:
arr = np.random.randint(10,50, size=(4,4))
print(arr)

[[49 29 29 46]
 [31 21 38 23]
 [12 29 23 37]
 [41 48 29 25]]


In [33]:
print('8x2')
print(arr.reshape(8,2))

8x2
[[49 29]
 [29 46]
 [31 21]
 [38 23]
 [12 29]
 [23 37]
 [41 48]
 [29 25]]


In [37]:
print(x[0,0])
print(x[0])
print(x[1])

7
[7 2 3]
[2 5 2]
